version: '3.9'

services:
  frontend:
    container_name: frontend_weather_app
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/weatherapp/frontend
      - /weatherapp/frontend/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    container_name: backend_weather_app
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/weatherapp/backend
      - /weatherapp/backend/node_modules