version: '3.8'
services:
  frontend:
    container_name: frontend_weather_app
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/weatherapp/frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    container_name: backend_weather_app
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/weatherapp/backend

  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend